# Generated by Django 3.1.7 on 2021-03-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='isim')),
                ('renk', models.CharField(choices=[('1', 'Siyah'), ('2', 'Beyaz'), ('3', 'Gold'), ('4', 'Gri'), ('5', 'Kırmızı')], default=1, max_length=10, verbose_name='renk')),
                ('fiyat', models.PositiveIntegerField(verbose_name='fiyat')),
                ('yeniFiyat', models.PositiveIntegerField(verbose_name='yeni Fiyat')),
                ('hafıza', models.CharField(choices=[('1', '16 gb'), ('2', '32'), ('3', '64'), ('4', '128'), ('5', '256')], default=1, max_length=20, verbose_name='hafıza')),
                ('bellek', models.CharField(choices=[('1', '2 gb'), ('2', '4 gb'), ('3', '6 gb'), ('4', '8 gb')], default=1, max_length=20, verbose_name='rem')),
                ('kamera', models.CharField(choices=[('1', '12'), ('2', '16'), ('3', '21')], default=1, max_length=20, verbose_name='MegaPixel')),
            ],
        ),
    ]
