# Generated by Django 3.1.7 on 2021-03-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_phonemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='kategori')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\windows\\Desktop\\django\\e_ticaret\\media'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='kategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.kategory'),
        ),
    ]
