# Generated by Django 3.1.7 on 2021-03-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210319_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='kategory',
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='kategorys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.kategory'),
        ),
    ]
