# Generated by Django 3.1.7 on 2021-03-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210320_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='yayinda_mi',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='yaynda mı'),
        ),
    ]
