# Generated by Django 3.1.7 on 2021-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210320_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='stok',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='stok'),
        ),
    ]
