# Generated by Django 3.1.7 on 2021-03-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcard', '0003_auto_20210328_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcardmodel',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='shopcardmodel',
            name='totalprice',
            field=models.IntegerField(),
        ),
    ]
