# Generated by Django 3.1.7 on 2021-03-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcard', '0005_remove_shopcardmodel_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcard_item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
