# Generated by Django 3.1.7 on 2021-03-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcard', '0007_shopcard_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcardmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
